services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistics_app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - logistics
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: logistics_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - logistics

  mysql:
    image: mysql:8.0
    container_name: logistics_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: logistics_api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - logistics

  redis:
    image: redis:alpine
    container_name: logistics_redis
    restart: unless-stopped
    networks:
      - logistics

networks:
  logistics:

volumes:
  dbdata: